name: Deploy Page
on: [push]
jobs:
  deploy_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-build-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{ runner.OS }}-build-${{ runner.OS }}-
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Build
        run: yarn run build
        env:
          NODE_ENV: production
          CI: false
      - name: Copy index.html 404.html
        run: cp dist/index.html dist/404.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: bot.minibox.xyz
          publish_dir: ./dist
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_branch: gh-pages
